// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package menus

import (
	"gf-vue-admin/app/admin/api/menus"
)

type ControllerV1 struct{}

func NewV1() menus.IMenusV1 {
	return &ControllerV1{}
}
