// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package roles

import (
	"gf-vue-admin/app/admin/api/roles"
)

type ControllerV1 struct{}

func NewV1() roles.IRolesV1 {
	return &ControllerV1{}
}