// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gf-vue-admin/app/admin/internal/dao/internal"
)

// adminUsersDao is the data access object for the table admin_users.
// You can define custom methods on it to extend its functionality as needed.
type adminUsersDao struct {
	*internal.AdminUsersDao
}

var (
	// AdminUsers is a globally accessible object for table admin_users operations.
	AdminUsers = adminUsersDao{internal.NewAdminUsersDao()}
)

// Add your custom methods and functionality below.
